name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: lower-repo
        shell: pwsh
        run: |
          echo "GITHUB_REPO_OWNER=$($env:GITHUB_REPOSITORY_OWNER.ToLowerInvariant())" >> "$env:GITHUB_OUTPUT"
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          tags: ghcr.io/${{ steps.lower-repo.outputs.GITHUB_REPO_OWNER }}/portal-integrations-bot:latest
          provenance: false              